version: '3'
services:
  allure:
    container_name: allure_test_mobile
    environment:
      TZ: "Europe/Samara"
    build:
      context: ${PWD}
      dockerfile: ./docker/allure-report/Dockerfile
    volumes:
      - ../allure-results:/var/allure-results/
    ports:
      - "35223:35223"
    command: sh -c "allure serve /var/allure-results --port 35223"
  python:
    container_name: pytest_test_mobile
    environment:
      TZ: "Europe/Samara"
    build:
      context: ${PWD}
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ../pyproject.toml:/var/pythonproject/pyproject.toml
      - ../README.md:/var/pythonproject/README.md
      - ../wikipedia:/var/pythonproject/wikipedia/
      - ../tests:/var/pythonproject/tests/
      - ../allure-results:/var/pythonproject/allure-results/
      - ../config.test.json:/var/pythonproject/config.test.json
    command: sh -c "poetry install && poetry run pytest tests/test_setting.py --env=test --driver=browserstack --platformVersion=10.0 --deviceName='Samsung Galaxy S20 Ultra'"
